### ISSUE TITLE
Artifactory response: 405 Method Not Allowed

### ISSUE THREAD

**Issue by tgatinea** [jfrog/jfrog-client-go#136]
I'm trying to download a file from an Artifactory repository.

I'm using jfrog-client-go version v0.9.0

        const artifactoryUrl = "My Artifactory URL"

	rtDetails := auth.NewArtifactoryDetails()
	rtDetails.SetUrl(artifactoryUrl)

	serviceConfig, err := config.NewConfigBuilder().
		SetArtDetails(rtDetails).
		SetDryRun(false).
		Build()
	if err != nil {
		panic(err)
	}

	rtManager, err := artifactory.New(&rtDetails, serviceConfig)
	if err != nil {
		panic(err)
	}

	params := services.NewDownloadParams()
	params.Target = "/tmp/file.json"
	params.Pattern = "path to my file.json"

	params.Recursive = true
	params.Regexp = false
	params.IncludeDirs = false
	params.Flat = true
	params.Explode = false
	params.Symlink = false
	params.Retries = 5

	_, _, err = rtManager.DownloadFiles(params)

The code rtManager.DownloadFiles(params) leads to do a SendPost() from the code client.go of jfrog-client-go that fails with:
Artifactory response: 405 Method Not Allowed

Note that if I do a "curl -X POST" with the URL of the file that I want to recover from artifactory then I get the same issue 405 while it works like a charm with a "curl -X GET"

Did I miss something in the params structure ?
Should it be SendGet() instead of SendPost() ?

**Comment by eyalbe4** [comment]
@tgatinea,
The DownloadFiles API starts by sending an AQL search to Artifactory using POST. The actual download requests which follow are GET requests. I am not sure why you get 405 response for the POST request. I suggest debugging the code to see if indeed it is the AQL request which fails. Yoy can try invoking other POST requests to try and figure out what's going on. Does all POST requests get blocked? For additional troubleshooting, you can try invoking JFrog CLI, which uses the same code when downloading files. I'm curious to know the root cause, so feel free to share your findings.

**Comment by tgatinea** [comment]
I've found my issue. 
It was actually failing into the AQL POST, but I saw that my URL artifactoryUrl = "My Artifactory URL" was in fact containing a part of the path of my file.
After moving this part into params.Pattern, it all worked like a charm.
Sorry for this inconvience.
