### ISSUE TITLE
#299 broke interface for DownloadFiles

### ISSUE THREAD

**Issue by ebilling** [jfrog/jfrog-client-go#309]
When #299 was implemented, it seems that the second variable returned is no long the number of expected files, it's now returning the number of failures.  While that is completely reasonable, the interface and the function manager.DownloadFiles both expect something else.

DownloadFiles(params ...services.DownloadParams) (totalDownloaded, **totalExpected** int, err error)

**Expected behavior**
Either the interface needs to change to totalFailed or ArtifactoryServicesManagerImp.DownloadFiles needs to change to return totalDownloaded+totalFailed.

**Versions**
- JFrog Go client version: v0.20.1

**Comment by asafgabai** [comment]
Hi @ebilling,
Thanks for reporting this issue.
As part of changing the results of the upload and download operations, we decided to change the return values of this function so it'll return the number of files that failed to be downloaded instead of the number of expected files (it was the only operation to return the number of expected files, and we wanted it to be the same as the results of the other operations).
Unfortunately, I accidentally didn't change the name of this return value in the function.
I opened a pull request for fixing it (#311).
